server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: hrs-api
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/hrs_db?serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        format_sql: true
    show-sql: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    issuer: ${JWT_TOKEN_ISSUER}
    expiry-duration-seconds: ${JWT_TOKEN_EXPIRY_DURATION_SECONDS}